In [66]:
import numpy as np
import math

In [67]:
imgs = np.loadtxt("images_1.np").reshape(1,2,6,6)
kernel = np.loadtxt("kernel_3.np").reshape(3,2,3,3)
bias = np.loadtxt("bias_3.np").reshape(3)

In [68]:
channels, X, Y = imgs[0].shape

In [69]:
p = 0

def get_x():
    return X + p * 2

def get_y():
    return Y + p * 2

def get_win_val(w, i, j, s, ch, k, img):    
    h_slides = math.floor((get_y()-k)/s) + 1
    v_slides = math.floor((get_x()-k)/s) + 1
    
    r = math.floor(w / h_slides)
    c = w % h_slides
    x = (r * s) + i - p
    y = (c * s) + j - p
    
    if x < 0 or y < 0 or x >= X or y >= Y:
        return 0
    
    return imgs[img][ch][x][y]

def img_to_conv2d():
    s = 1
    k = 3

    h_slides = math.floor((get_y()-k)/s) + 1
    v_slides = math.floor((get_x()-k)/s) + 1
    
    windows = h_slides * v_slides
    
    data = []
    
    for w in range(windows):
        row = []
        for c in range(channels):
            for i in range(k):
                for j in range(k):
                    row.append(get_win_val(w, i, j, s, c, k, 0))
        data.append(row)
    
    return np.array(data)

In [70]:
data = img_to_conv2d()
data = np.hstack((data, np.ones(data.shape[0]).reshape(-1, 1)))
for i in range(data.shape[0]):
    print(data[i].tolist())

[0.15955305524877594, 0.8490690087375984, 0.5456136222214727, 0.8853629058368967, 0.7254401358430989, 0.30213657418733375, 0.6813981740742285, 0.45835188596948095, 0.4002506138703792, 0.09849916004483994, 0.169140409260646, 0.892509682689015, 0.5331381259882667, 0.9516638506590015, 0.4389646044361254, 0.8469585022518668, 0.43609608474088934, 0.5567002733150794, 1.0]
[0.8490690087375984, 0.5456136222214727, 0.8960437624473898, 0.7254401358430989, 0.30213657418733375, 0.2439179574605711, 0.45835188596948095, 0.4002506138703792, 0.12925077499927617, 0.169140409260646, 0.892509682689015, 0.5272782984630022, 0.9516638506590015, 0.4389646044361254, 0.6531780693339448, 0.43609608474088934, 0.5567002733150794, 0.5485621768253884, 1.0]
[0.5456136222214727, 0.8960437624473898, 0.3766046215214379, 0.30213657418733375, 0.2439179574605711, 0.8367922988879591, 0.4002506138703792, 0.12925077499927617, 0.38525405907157717, 0.892509682689015, 0.5272782984630022, 0.8736680101933795, 0.4389646044361254, 

In [71]:
arr = [kernel[i].flatten() for i in range(kernel.shape[0])]
arr = np.array(arr)
arr = arr.T
arr = np.vstack((arr, bias.reshape(1, 3)))
arr

array([[0.96844024, 0.20287251, 0.37104108],
       [0.91677037, 0.63202806, 0.65179618],
       [0.20084168, 0.87074152, 0.47142603],
       [0.51737026, 0.50011759, 0.17087244],
       [0.84232667, 0.21778542, 0.01127146],
       [0.16916628, 0.02711159, 0.12772858],
       [0.00337454, 0.69487962, 0.86150483],
       [0.52294908, 0.59547085, 0.8443549 ],
       [0.97996873, 0.4803164 , 0.55282022],
       [0.49270656, 0.3663493 , 0.71372867],
       [0.28457836, 0.1255844 , 0.95544612],
       [0.4204916 , 0.77317302, 0.34553299],
       [0.38666854, 0.00984027, 0.09791882],
       [0.74145295, 0.37000069, 0.69473835],
       [0.77173518, 0.05565784, 0.28326671],
       [0.16400922, 0.37260327, 0.32258273],
       [0.20366011, 0.56026268, 0.91501908],
       [0.53234345, 0.10974279, 0.207473  ],
       [0.51915282, 0.34316147, 0.91806065]])

In [72]:
data@arr

array([[5.56267416, 4.68508028, 5.34701042],
       [5.2636885 , 4.01907079, 5.47665681],
       [5.50856595, 4.0643638 , 5.63534799],
       [5.81793048, 3.32128891, 5.43088991],
       [6.17222889, 4.15730646, 6.12195393],
       [4.96573353, 3.91459051, 5.59096801],
       [4.2126624 , 3.58107053, 5.02729167],
       [5.11731713, 3.28523716, 4.7555589 ],
       [6.13268723, 4.15682821, 5.48800541],
       [5.58181855, 4.25900174, 5.74191944],
       [4.28855602, 4.13251183, 5.40665918],
       [3.95228251, 3.50958781, 5.12752524],
       [5.60417034, 4.20573799, 5.66475913],
       [5.81319056, 4.02033004, 5.51482169],
       [4.87948909, 3.41492845, 4.61672905],
       [4.49006804, 3.31404358, 3.96031835]])

In [45]:
b = np.array([0.16914,0.89251,0.533138,0.951664,0.438965,0.846959,0.436096,0.5567,1,0,
0.89251,0.527278,0.951664,0.438965,0.653178,0.436096,0.5567,0.548562,1,0,
0.527278,0.873668,0.438965,0.653178,0.436289,0.5567,0.548562,0.870072,1,0,
0.873668,0.12653,0.653178,0.436289,0.908437,0.548562,0.870072,0.606297,1,0,
0.951664,0.438965,0.846959,0.436096,0.5567,0.363921,0.242119,0.485117,1,0,
0.438965,0.653178,0.436096,0.5567,0.548562,0.242119,0.485117,0.446745,1,0,
0.653178,0.436289,0.5567,0.548562,0.870072,0.485117,0.446745,0.0650731,1,0,
0.436289,0.908437,0.548562,0.870072,0.606297,0.446745,0.0650731,0.710499,1,0,
0.436096,0.5567,0.363921,0.242119,0.485117,0.49206,0.51518,0.652342,1,0,
0.5567,0.548562,0.242119,0.485117,0.446745,0.51518,0.652342,0.2037,1,0]).reshape(10,10)
d = np.array([0.548562,0.870072,0.485117,0.446745,0.0650731,0.652342,0.2037,0.590233,1,0,
0.870072,0.606297,0.446745,0.0650731,0.710499,0.2037,0.590233,0.842361,1,0,
0.242119,0.485117,0.49206,0.51518,0.652342,0.15014,0.922943,0.910163,1,0,
0.485117,0.446745,0.51518,0.652342,0.2037,0.922943,0.910163,0.91172,1,0,
0.446745,0.0650731,0.652342,0.2037,0.590233,0.910163,0.91172,0.00540243,1,0,
0.0650731,0.710499,0.2037,0.590233,0.842361,0.91172,0.00540243,0.916561,1,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,]).reshape(10,10)
a = np.array([0.159553,0.849069,0.545614,0.885363,0.72544,0.302137,0.681398,0.458352,0.400251,0.0984992,
0.849069,0.545614,0.896044,0.72544,0.302137,0.243918,0.458352,0.400251,0.129251,0.16914,
0.545614,0.896044,0.376605,0.302137,0.243918,0.836792,0.400251,0.129251,0.385254,0.89251,
0.896044,0.376605,0.326049,0.243918,0.836792,0.00677764,0.129251,0.385254,0.568888,0.527278,
0.885363,0.72544,0.302137,0.681398,0.458352,0.400251,0.61426,0.938278,0.617417,0.533138,
0.72544,0.302137,0.243918,0.458352,0.400251,0.129251,0.938278,0.617417,0.25137,0.951664,
0.302137,0.243918,0.836792,0.400251,0.129251,0.385254,0.617417,0.25137,0.418694,0.438965,
0.243918,0.836792,0.00677764,0.129251,0.385254,0.568888,0.25137,0.418694,0.27364,0.653178,
0.681398,0.458352,0.400251,0.61426,0.938278,0.617417,0.383435,0.523062,0.982311,0.846959,
0.458352,0.400251,0.129251,0.938278,0.617417,0.25137,0.523062,0.982311,0.953668,0.436096,]).reshape(10,10)
c = np.array([0.400251,0.129251,0.385254,0.617417,0.25137,0.418694,0.982311,0.953668,0.259095,0.5567,
0.129251,0.385254,0.568888,0.25137,0.418694,0.27364,0.953668,0.259095,0.0291897,0.548562,
0.61426,0.938278,0.617417,0.383435,0.523062,0.982311,0.56839,0.602344,0.162163,0.363921,
0.938278,0.617417,0.25137,0.523062,0.982311,0.953668,0.602344,0.162163,0.321724,0.242119,
0.617417,0.25137,0.418694,0.982311,0.953668,0.259095,0.162163,0.321724,0.340417,0.485117,
0.25137,0.418694,0.27364,0.953668,0.259095,0.0291897,0.321724,0.340417,0.0515995,0.446745,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,]).reshape(10,10)
im = np.vstack((np.hstack((a, b)), np.hstack((c,d))))

In [46]:
a = np.array([0.96844,0.91677,0.200842,0.51737,0.842327,0.169166,0.00337454,0.522949,0.519153,0.492707,
0.202873,0.632028,0.870742,0.500118,0.217785,0.0271116,0.69488,0.595471,0.343161,0.366349,
0.371041,0.651796,0.471426,0.170872,0.0112715,0.127729,0.861505,0.844355,0.918061,0.713729,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,]).reshape(10,10)
b = np.array([0.284578,0.420492,0.386669,0.741453,0.771735,0.164009,0.20366,0.532343,0.519153,0,
0.125584,0.773173,0.00984027,0.370001,0.0556578,0.372603,0.560263,0.109743,0.343161,0,
0.955446,0.345533,0.0979188,0.694738,0.283267,0.322583,0.915019,0.207473,0.918061,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,]).reshape(10,10)
ke = np.hstack((a,b))

In [58]:
for i in range(im.shape[0]):
    print(im[i].tolist())

[0.159553, 0.849069, 0.545614, 0.885363, 0.72544, 0.302137, 0.681398, 0.458352, 0.400251, 0.0984992, 0.16914, 0.89251, 0.533138, 0.951664, 0.438965, 0.846959, 0.436096, 0.5567, 1.0, 0.0]
[0.849069, 0.545614, 0.896044, 0.72544, 0.302137, 0.243918, 0.458352, 0.400251, 0.129251, 0.16914, 0.89251, 0.527278, 0.951664, 0.438965, 0.653178, 0.436096, 0.5567, 0.548562, 1.0, 0.0]
[0.545614, 0.896044, 0.376605, 0.302137, 0.243918, 0.836792, 0.400251, 0.129251, 0.385254, 0.89251, 0.527278, 0.873668, 0.438965, 0.653178, 0.436289, 0.5567, 0.548562, 0.870072, 1.0, 0.0]
[0.896044, 0.376605, 0.326049, 0.243918, 0.836792, 0.00677764, 0.129251, 0.385254, 0.568888, 0.527278, 0.873668, 0.12653, 0.653178, 0.436289, 0.908437, 0.548562, 0.870072, 0.606297, 1.0, 0.0]
[0.885363, 0.72544, 0.302137, 0.681398, 0.458352, 0.400251, 0.61426, 0.938278, 0.617417, 0.533138, 0.951664, 0.438965, 0.846959, 0.436096, 0.5567, 0.363921, 0.242119, 0.485117, 1.0, 0.0]
[0.72544, 0.302137, 0.243918, 0.458352, 0.400251, 0.129251, 

In [48]:
im@ke.T

array([[5.37823296, 4.63018496, 5.49319885, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [5.2041284 , 4.00134442, 5.52386542, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [5.33103516, 4.01152509, 5.77605965, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [5.55577665, 3.24326191, 5.63867055, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [5.88771365, 4.07262558, 6.34746097, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [4.84989905, 3.8801146 , 5.68277985, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [4.01972171, 3.52364451, 5.18021625, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [4.99121812, 3.2477049 , 4.8555027

In [50]:
im[:16,:19]@ke[:3,:19].T

array([[5.37823296, 4.63018496, 5.49319885],
       [5.2041284 , 4.00134442, 5.52386542],
       [5.33103516, 4.01152509, 5.77605965],
       [5.55577665, 3.24326191, 5.63867055],
       [5.88771365, 4.07262558, 6.34746097],
       [4.84989905, 3.8801146 , 5.68277985],
       [4.01972171, 3.52364451, 5.18021625],
       [4.99121812, 3.2477049 , 4.85550276],
       [5.68002355, 4.02209968, 5.84678686],
       [5.14235353, 4.12820174, 6.09023833],
       [4.16916098, 4.09697583, 5.5012917 ],
       [3.9388307 , 3.50558334, 5.13818621],
       [5.52944366, 4.18349794, 5.72398882],
       [5.66493549, 3.97620483, 5.63232959],
       [4.72262042, 3.36823876, 4.74106395],
       [4.46628979, 3.30696637, 3.97916503]])

In [56]:
data-im[:16,:19]

array([[ 5.52487759e-08,  8.73759842e-09, -3.77778527e-07,
        -9.41631033e-08,  1.35843099e-07, -4.25812666e-07,
         1.74074229e-07, -1.14030519e-07, -3.86129621e-07,
        -3.99551601e-08,  4.09260646e-07, -3.17310985e-07,
         1.25988267e-07, -1.49340998e-07, -3.95563875e-07,
        -4.97748133e-07,  8.47408894e-08,  2.73315079e-07,
         0.00000000e+00],
       [ 8.73759842e-09, -3.77778527e-07, -2.37552610e-07,
         1.35843099e-07, -4.25812666e-07, -4.25394289e-08,
        -1.14030519e-07, -3.86129621e-07, -2.25000724e-07,
         4.09260646e-07, -3.17310985e-07,  2.98463002e-07,
        -1.49340998e-07, -3.95563875e-07,  6.93339448e-08,
         8.47408894e-08,  2.73315079e-07,  1.76825388e-07,
         0.00000000e+00],
       [-3.77778527e-07, -2.37552610e-07, -3.78478562e-07,
        -4.25812666e-07, -4.25394289e-08,  2.98887959e-07,
        -3.86129621e-07, -2.25000724e-07,  5.90715772e-08,
        -3.17310985e-07,  2.98463002e-07,  1.01933795e-08,
    