In [114]:
import numpy as np
import math

In [115]:
imgs = np.random.rand(1,2,6,6)
header = "{},{},{},{}".format(*imgs.shape)
np.savetxt("images.np", imgs.flatten(), header=header)

In [123]:
imgs = np.loadtxt("images_1.np").reshape(1,2,6,6)
imgs

array([[[[0.15955306, 0.84906901, 0.54561362, 0.89604376, 0.37660462,
          0.32604895],
         [0.88536291, 0.72544014, 0.30213657, 0.24391796, 0.8367923 ,
          0.00677764],
         [0.68139817, 0.45835189, 0.40025061, 0.12925077, 0.38525406,
          0.56888845],
         [0.61425965, 0.93827786, 0.61741657, 0.25136994, 0.41869429,
          0.27364   ],
         [0.38343472, 0.52306167, 0.9823107 , 0.95366812, 0.25909526,
          0.02918973],
         [0.5683895 , 0.60234376, 0.1621629 , 0.32172377, 0.34041692,
          0.05159952]],

        [[0.09849916, 0.16914041, 0.89250968, 0.5272783 , 0.87366801,
          0.12653044],
         [0.53313813, 0.95166385, 0.4389646 , 0.65317807, 0.43628923,
          0.90843706],
         [0.8469585 , 0.43609608, 0.55670027, 0.54856218, 0.8700725 ,
          0.60629741],
         [0.36392068, 0.24211918, 0.48511723, 0.44674531, 0.06507306,
          0.71049912],
         [0.49205998, 0.51518035, 0.65234204, 0.20369967, 0.5902329 

In [124]:
channels, X, Y = imgs[0].shape

In [125]:
p = 2

def get_x():
    return X + p * 2

def get_y():
    return Y + p * 2

def get_win_val(w, i, j, s, ch, k, img):    
    h_slides = math.floor((get_x()-k)/s) + 1
    v_slides = math.floor((get_y()-k)/s) + 1
    
    r = math.floor(w / h_slides)
    c = w % h_slides
    x = (r * s) + i - p
    y = (c * s) + j - p
    
    if x < 0 or y < 0 or x >= X or y >= Y:
        return 0
    
    return imgs[img][ch][x][y]

def img_to_conv2d():
    s = 1
    k = 3

    h_slides = math.floor((get_x()-k)/s) + 1
    v_slides = math.floor((get_y()-k)/s) + 1
    
    windows = h_slides * v_slides
    
    data = []
    
    for w in range(windows):
        row = []
        for c in range(channels):
            for i in range(k):
                for j in range(k):
                    row.append(get_win_val(w, i, j, s, c, k, 0))
        data.append(row)
    
    return np.array(data)

In [126]:
data = img_to_conv2d()
data.shape

(64, 18)

In [94]:
d_imgs = []
p = 2
for c in range(channels):
    d_imgs.append(np.pad(imgs[0][c], ((p,p),(p,p)), 'constant'))
d_imgs = np.array(d_imgs).reshape(1,2,10,10)
d_imgs.shape

(1, 2, 10, 10)

In [95]:
channels, X, Y = d_imgs[0].shape 

In [98]:
def get_win_val(w, i, j, s, ch, k, img):    
    h_slides = math.floor((X-k)/s) + 1
    v_slides = math.floor((Y-k)/s) + 1
    
    r = math.floor(w / h_slides)
    c = w % h_slides
    x = (r * s) + i
    y = (c * s) + j
    
    return d_imgs[img][ch][x][y]

def img_to_conv2d():
    s = 1
    k = 3

    h_slides = math.floor((X-k)/s) + 1
    v_slides = math.floor((Y-k)/s) + 1
    
    windows = h_slides * v_slides
    
    data = []
    
    for w in range(windows):
        row = []
        for c in range(channels):
            for i in range(k):
                for j in range(k):
                    row.append(get_win_val(w, i, j, s, c, k, 0))
        data.append(row)
    
    return np.array(data)

In [99]:
d_data = img_to_conv2d()
d_data.shape

(64, 18)

In [100]:
np.array_equal(d_data, data)

True

In [127]:
for i in range(data.shape[0]):
    print(data[i].tolist())

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.15955305524877594, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.09849916004483994]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.15955305524877594, 0.8490690087375984, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.09849916004483994, 0.169140409260646]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.15955305524877594, 0.8490690087375984, 0.5456136222214727, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.09849916004483994, 0.169140409260646, 0.892509682689015]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8490690087375984, 0.5456136222214727, 0.8960437624473898, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.169140409260646, 0.892509682689015, 0.5272782984630022]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5456136222214727, 0.8960437624473898, 0.3766046215214379, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.892509682689015, 0.5272782984630022, 0.8736680101933795]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8960437624473898, 0.3766046215214379, 0.3260489539047057, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5272782984630022, 0.8736680101933795, 0.1265304400449001]
[0.0

In [130]:
t = np.random.rand(4,2)
t

array([[0.62817478, 0.47104385],
       [0.79948237, 0.11602758],
       [0.2107311 , 0.58653563],
       [0.71798634, 0.47725836]])

In [133]:
k = t.T
k

array([[0.62817478, 0.79948237, 0.2107311 , 0.71798634],
       [0.47104385, 0.11602758, 0.58653563, 0.47725836]])

In [134]:
k.T

array([[0.62817478, 0.47104385],
       [0.79948237, 0.11602758],
       [0.2107311 , 0.58653563],
       [0.71798634, 0.47725836]])

In [135]:
imgs = np.random.rand(3,2,3,3)
header = "{},{},{},{}".format(*imgs.shape)
np.savetxt("kernel_3.np", imgs.flatten(), header=header)

In [138]:
imgs = np.random.rand(3,1)
header = "{},{}".format(*imgs.shape)
np.savetxt("bias_3.np", imgs.flatten(), header=header)

In [139]:
imgs

array([[0.51915282],
       [0.34316147],
       [0.91806065]])

In [143]:
j = np.array([0.96844,0.91677,0.200842,0.51737,0.842327,0.169166,0.00337454,0.522949,0.519153,0.492707,
0.202873,0.632028,0.870742,0.500118,0.217785,0.0271116,0.69488,0.595471,0.343161,0.366349,
0.371041,0.651796,0.471426,0.170872,0.0112715,0.127729,0.861505,0.844355,0.918061,0.713729,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0]).reshape(10,10)
k = np.array([0.284578,0.420492,0.386669,0.741453,0.771735,0.164009,0.20366,0.532343,0.519153,0,
0.125584,0.773173,0.00984027,0.370001,0.0556578,0.372603,0.560263,0.109743,0.343161,0,
0.955446,0.345533,0.0979188,0.694738,0.283267,0.322583,0.915019,0.207473,0.918061,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0]).reshape(10,10)
kk = np.hstack((j,k))
kk

array([[0.96844   , 0.91677   , 0.200842  , 0.51737   , 0.842327  ,
        0.169166  , 0.00337454, 0.522949  , 0.519153  , 0.492707  ,
        0.284578  , 0.420492  , 0.386669  , 0.741453  , 0.771735  ,
        0.164009  , 0.20366   , 0.532343  , 0.519153  , 0.        ],
       [0.202873  , 0.632028  , 0.870742  , 0.500118  , 0.217785  ,
        0.0271116 , 0.69488   , 0.595471  , 0.343161  , 0.366349  ,
        0.125584  , 0.773173  , 0.00984027, 0.370001  , 0.0556578 ,
        0.372603  , 0.560263  , 0.109743  , 0.343161  , 0.        ],
       [0.371041  , 0.651796  , 0.471426  , 0.170872  , 0.0112715 ,
        0.127729  , 0.861505  , 0.844355  , 0.918061  , 0.713729  ,
        0.955446  , 0.345533  , 0.0979188 , 0.694738  , 0.283267  ,
        0.322583  , 0.915019  , 0.207473  , 0.918061  , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0

In [144]:
kk.T

array([[0.96844   , 0.202873  , 0.371041  , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.91677   , 0.632028  , 0.651796  , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.200842  , 0.870742  , 0.471426  , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.51737   , 0.500118  , 0.170872  , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.842327  , 0.217785  , 0.0112715 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.169166  , 0.0271116 , 0.127729  , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.00337454, 0.69488   , 0.861505  , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.522949  , 0.595471  , 0.844355 